#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from mdl.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "mdl.y"

  /* C declarations */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "parser.h"
#include "matrix.h"

#define YYERROR_VERBOSE 1

  SYMTAB *s;
  struct light *l;
  struct constants *c;
  struct command op[MAX_COMMANDS];
  struct matrix *m;
  int lastop=0;
  int lineno=0;
  
#line 23 "mdl.y"
typedef union{
  double val;
  char string[255];
} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	COMMENT	258
#define	DOUBLE	259
#define	LIGHT	260
#define	AMBIENT	261
#define	CONSTANTS	262
#define	SAVE_COORDS	263
#define	CAMERA	264
#define	SPHERE	265
#define	TORUS	266
#define	BOX	267
#define	LINE	268
#define	CS	269
#define	MESH	270
#define	TEXTURE	271
#define	STRING	272
#define	SET	273
#define	MOVE	274
#define	SCALE	275
#define	ROTATE	276
#define	BASENAME	277
#define	SAVE_KNOBS	278
#define	TWEEN	279
#define	FRAMES	280
#define	VARY	281
#define	PUSH	282
#define	POP	283
#define	SAVE	284
#define	GENERATE_RAYFILES	285
#define	SHADING	286
#define	SHADING_TYPE	287
#define	SETKNOBS	288
#define	FOCAL	289
#define	DISPLAY	290
#define	WEB	291
#define	CO	292


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int COMMENT;
static const int DOUBLE;
static const int LIGHT;
static const int AMBIENT;
static const int CONSTANTS;
static const int SAVE_COORDS;
static const int CAMERA;
static const int SPHERE;
static const int TORUS;
static const int BOX;
static const int LINE;
static const int CS;
static const int MESH;
static const int TEXTURE;
static const int STRING;
static const int SET;
static const int MOVE;
static const int SCALE;
static const int ROTATE;
static const int BASENAME;
static const int SAVE_KNOBS;
static const int TWEEN;
static const int FRAMES;
static const int VARY;
static const int PUSH;
static const int POP;
static const int SAVE;
static const int GENERATE_RAYFILES;
static const int SHADING;
static const int SHADING_TYPE;
static const int SETKNOBS;
static const int FOCAL;
static const int DISPLAY;
static const int WEB;
static const int CO;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,COMMENT=258
	,DOUBLE=259
	,LIGHT=260
	,AMBIENT=261
	,CONSTANTS=262
	,SAVE_COORDS=263
	,CAMERA=264
	,SPHERE=265
	,TORUS=266
	,BOX=267
	,LINE=268
	,CS=269
	,MESH=270
	,TEXTURE=271
	,STRING=272
	,SET=273
	,MOVE=274
	,SCALE=275
	,ROTATE=276
	,BASENAME=277
	,SAVE_KNOBS=278
	,TWEEN=279
	,FRAMES=280
	,VARY=281
	,PUSH=282
	,POP=283
	,SAVE=284
	,GENERATE_RAYFILES=285
	,SHADING=286
	,SHADING_TYPE=287
	,SETKNOBS=288
	,FOCAL=289
	,DISPLAY=290
	,WEB=291
	,CO=292


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::COMMENT=258;
const int YY_parse_CLASS::DOUBLE=259;
const int YY_parse_CLASS::LIGHT=260;
const int YY_parse_CLASS::AMBIENT=261;
const int YY_parse_CLASS::CONSTANTS=262;
const int YY_parse_CLASS::SAVE_COORDS=263;
const int YY_parse_CLASS::CAMERA=264;
const int YY_parse_CLASS::SPHERE=265;
const int YY_parse_CLASS::TORUS=266;
const int YY_parse_CLASS::BOX=267;
const int YY_parse_CLASS::LINE=268;
const int YY_parse_CLASS::CS=269;
const int YY_parse_CLASS::MESH=270;
const int YY_parse_CLASS::TEXTURE=271;
const int YY_parse_CLASS::STRING=272;
const int YY_parse_CLASS::SET=273;
const int YY_parse_CLASS::MOVE=274;
const int YY_parse_CLASS::SCALE=275;
const int YY_parse_CLASS::ROTATE=276;
const int YY_parse_CLASS::BASENAME=277;
const int YY_parse_CLASS::SAVE_KNOBS=278;
const int YY_parse_CLASS::TWEEN=279;
const int YY_parse_CLASS::FRAMES=280;
const int YY_parse_CLASS::VARY=281;
const int YY_parse_CLASS::PUSH=282;
const int YY_parse_CLASS::POP=283;
const int YY_parse_CLASS::SAVE=284;
const int YY_parse_CLASS::GENERATE_RAYFILES=285;
const int YY_parse_CLASS::SHADING=286;
const int YY_parse_CLASS::SHADING_TYPE=287;
const int YY_parse_CLASS::SETKNOBS=288;
const int YY_parse_CLASS::FOCAL=289;
const int YY_parse_CLASS::DISPLAY=290;
const int YY_parse_CLASS::WEB=291;
const int YY_parse_CLASS::CO=292;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		176
#define	YYFLAG		-32768
#define	YYNTBASE	38

#define YYTRANSLATE(x) ((unsigned)(x) <= 292 ? yytranslate[x] : 40)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     1,     4,     6,    12,    19,    26,    34,    41,    49,
    57,    66,    74,    83,    92,   102,   110,   119,   128,   138,
   147,   157,   167,   178,   182,   187,   193,   199,   204,   210,
   215,   220,   224,   226,   228,   230,   233,   242,   254,   269,
   272,   280,   295,   299,   302,   305,   311,   314,   321,   324,
   327,   330,   332,   337
};

static const short yyrhs[] = {    -1,
    38,    39,     0,     3,     0,    10,     4,     4,     4,     4,
     0,    10,     4,     4,     4,     4,    17,     0,    10,    17,
     4,     4,     4,     4,     0,    10,    17,     4,     4,     4,
     4,    17,     0,    11,     4,     4,     4,     4,     4,     0,
    11,     4,     4,     4,     4,     4,    17,     0,    11,    17,
     4,     4,     4,     4,     4,     0,    11,    17,     4,     4,
     4,     4,     4,    17,     0,    12,     4,     4,     4,     4,
     4,     4,     0,    12,     4,     4,     4,     4,     4,     4,
    17,     0,    12,    17,     4,     4,     4,     4,     4,     4,
     0,    12,    17,     4,     4,     4,     4,     4,     4,    17,
     0,    13,     4,     4,     4,     4,     4,     4,     0,    13,
     4,     4,     4,    17,     4,     4,     4,     0,    13,     4,
     4,     4,     4,     4,     4,    17,     0,    13,     4,     4,
     4,    17,     4,     4,     4,    17,     0,    13,    17,     4,
     4,     4,     4,     4,     4,     0,    13,    17,     4,     4,
     4,    17,     4,     4,     4,     0,    13,    17,     4,     4,
     4,     4,     4,     4,    17,     0,    13,    17,     4,     4,
     4,    17,     4,     4,     4,    17,     0,    15,    37,    17,
     0,    15,    17,    37,    17,     0,    15,    17,    37,    17,
    17,     0,    19,     4,     4,     4,    17,     0,    19,     4,
     4,     4,     0,    20,     4,     4,     4,    17,     0,    20,
     4,     4,     4,     0,    21,    17,     4,    17,     0,    21,
    17,     4,     0,    27,     0,    28,     0,    35,     0,    29,
    17,     0,     5,    17,     4,     4,     4,     4,     4,     4,
     0,     7,    17,     4,     4,     4,     4,     4,     4,     4,
     4,     4,     0,     7,    17,     4,     4,     4,     4,     4,
     4,     4,     4,     4,     4,     4,     4,     0,     8,    17,
     0,     9,     4,     4,     4,     4,     4,     4,     0,    16,
    17,     4,     4,     4,     4,     4,     4,     4,     4,     4,
     4,     4,     4,     0,    18,    17,     4,     0,    22,    17,
     0,    23,    17,     0,    24,     4,     4,    17,    17,     0,
    25,     4,     0,    26,    17,     4,     4,     4,     4,     0,
    31,    32,     0,    33,     4,     0,    34,     4,     0,    36,
     0,     6,     4,     4,     4,     0,    30,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    41,    42,    45,    47,    61,    75,    89,   105,   121,   136,
   152,   169,   187,   205,   222,   241,   259,   278,   296,   315,
   334,   353,   373,   393,   403,   413,   424,   436,   447,   459,
   470,   494,   517,   524,   531,   538,   546,   566,   594,   621,
   630,   645,   668,   678,   686,   693,   704,   712,   724,   732,
   739,   746,   753,   762
};

static const char * const yytname[] = {   "$","error","$illegal.","COMMENT",
"DOUBLE","LIGHT","AMBIENT","CONSTANTS","SAVE_COORDS","CAMERA","SPHERE","TORUS",
"BOX","LINE","CS","MESH","TEXTURE","STRING","SET","MOVE","SCALE","ROTATE","BASENAME",
"SAVE_KNOBS","TWEEN","FRAMES","VARY","PUSH","POP","SAVE","GENERATE_RAYFILES",
"SHADING","SHADING_TYPE","SETKNOBS","FOCAL","DISPLAY","WEB","CO","input","command",
""
};
#endif

static const short yyr1[] = {     0,
    38,    38,    39,    39,    39,    39,    39,    39,    39,    39,
    39,    39,    39,    39,    39,    39,    39,    39,    39,    39,
    39,    39,    39,    39,    39,    39,    39,    39,    39,    39,
    39,    39,    39,    39,    39,    39,    39,    39,    39,    39,
    39,    39,    39,    39,    39,    39,    39,    39,    39,    39,
    39,    39,    39,    39
};

static const short yyr2[] = {     0,
     0,     2,     1,     5,     6,     6,     7,     6,     7,     7,
     8,     7,     8,     8,     9,     7,     8,     8,     9,     8,
     9,     9,    10,     3,     4,     5,     5,     4,     5,     4,
     4,     3,     1,     1,     1,     2,     8,    11,    14,     2,
     7,    14,     3,     2,     2,     5,     2,     6,     2,     2,
     2,     1,     4,     1
};

static const short yydefact[] = {     1,
     0,     3,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,    33,    34,     0,    54,     0,     0,     0,    35,
    52,     2,     0,     0,     0,    40,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,    44,    45,     0,    47,     0,    36,    49,    50,
    51,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,    24,     0,    43,     0,     0,    32,
     0,     0,     0,    53,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,    25,     0,    28,    30,    31,     0,
     0,     0,     0,     0,     4,     0,     0,     0,     0,     0,
     0,     0,     0,    26,     0,    27,    29,    46,     0,     0,
     0,     0,     5,     6,     8,     0,     0,     0,     0,     0,
     0,     0,     0,    48,     0,     0,    41,     7,     9,    10,
    12,     0,    16,     0,     0,     0,     0,    37,     0,    11,
    13,    14,    18,    17,    20,     0,     0,     0,    15,    19,
    22,    21,     0,     0,    23,     0,    38,     0,     0,     0,
     0,     0,    39,    42,     0,     0
};

static const short yydefgoto[] = {     1,
    32
};

static const short yypact[] = {-32768,
     0,-32768,   -15,    13,   -13,    22,    39,    -3,    33,    34,
    36,    15,    27,    28,    42,    43,    31,    32,    40,    52,
    54,    44,-32768,-32768,    45,-32768,    35,    55,    56,-32768,
-32768,-32768,    59,    60,    61,-32768,    62,    64,    65,    66,
    67,    68,    69,    70,    71,    41,    63,    72,    73,    75,
    77,    78,-32768,-32768,    79,-32768,    80,-32768,-32768,-32768,
-32768,    81,    82,    83,    84,    85,    86,    87,    88,    89,
    90,    91,    92,    93,-32768,    94,-32768,    95,    96,    97,
    98,    99,   100,-32768,   101,   102,   103,   104,   105,   107,
   108,   109,    37,   112,   106,   113,   110,   111,-32768,   114,
   115,   116,   117,   118,   119,   120,   121,   122,   125,   126,
   128,   129,    38,-32768,   130,-32768,-32768,-32768,   131,   133,
   134,   135,-32768,   123,   124,   138,   139,   140,   141,   142,
   143,   144,   145,-32768,   146,   147,-32768,-32768,-32768,   136,
   137,   148,   149,   151,   152,   153,   154,-32768,   155,-32768,
-32768,   150,-32768,   156,   157,   158,   159,   160,-32768,-32768,
-32768,   161,   164,   165,-32768,   166,   167,   168,   171,   172,
   173,   175,-32768,-32768,   180,-32768
};

static const short yypgoto[] = {-32768,
-32768
};


#define	YYLAST		180


static const short yytable[] = {   175,
    38,    33,     2,    35,     3,     4,     5,     6,     7,     8,
     9,    10,    11,    39,    12,    13,    34,    14,    15,    16,
    17,    18,    19,    20,    21,    22,    23,    24,    25,    26,
    27,    46,    28,    29,    30,    31,    40,    42,    36,    44,
   111,   131,    37,    48,    49,    50,    51,    52,    53,    41,
    43,    47,    45,   112,   132,    55,    54,    56,    60,    61,
    57,    58,    62,    63,    64,    65,    59,    66,    67,    68,
    69,    70,    71,    72,    73,    76,    77,    74,    78,    75,
    79,    80,    81,    82,    83,    84,    85,    86,    87,    88,
    89,    90,    91,    92,    93,    94,     0,    96,    97,    98,
     0,     0,   101,   102,   103,   104,   105,   106,   107,    95,
   108,   109,   110,    99,   100,   113,   115,     0,   119,   120,
   121,   122,   114,   124,   125,   126,   116,   117,   127,   128,
   118,   129,   130,   133,   134,   123,   135,   136,   137,   138,
   139,   140,   141,   142,   143,   144,   145,   146,   147,   148,
   149,   152,   150,   151,   154,   155,   156,   157,   158,     0,
     0,   162,   163,   164,     0,   153,   159,   166,   167,   168,
   169,   170,   160,   161,   171,   172,   173,   165,   174,   176
};

static const short yycheck[] = {     0,
     4,    17,     3,    17,     5,     6,     7,     8,     9,    10,
    11,    12,    13,    17,    15,    16,     4,    18,    19,    20,
    21,    22,    23,    24,    25,    26,    27,    28,    29,    30,
    31,    17,    33,    34,    35,    36,     4,     4,    17,     4,
     4,     4,     4,    17,    17,     4,     4,    17,    17,    17,
    17,    37,    17,    17,    17,     4,    17,     4,     4,     4,
    17,    17,     4,     4,     4,     4,    32,     4,     4,     4,
     4,     4,     4,     4,     4,     4,     4,    37,     4,    17,
     4,     4,     4,     4,     4,     4,     4,     4,     4,     4,
     4,     4,     4,     4,     4,     4,    -1,     4,     4,     4,
    -1,    -1,     4,     4,     4,     4,     4,     4,     4,    17,
     4,     4,     4,    17,    17,     4,     4,    -1,     4,     4,
     4,     4,    17,     4,     4,     4,    17,    17,     4,     4,
    17,     4,     4,     4,     4,    17,     4,     4,     4,    17,
    17,     4,     4,     4,     4,     4,     4,     4,     4,     4,
     4,     4,    17,    17,     4,     4,     4,     4,     4,    -1,
    -1,     4,     4,     4,    -1,    17,    17,     4,     4,     4,
     4,     4,    17,    17,     4,     4,     4,    17,     4,     0
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 3:
#line 47 "mdl.y"
{;
    break;}
case 4:
#line 50 "mdl.y"
{
  lineno++;
  op[lastop].opcode = SPHERE;
  op[lastop].op.sphere.d[0] = yyvsp[-3].val;
  op[lastop].op.sphere.d[1] = yyvsp[-2].val;
  op[lastop].op.sphere.d[2] = yyvsp[-1].val;
  op[lastop].op.sphere.d[3] = 0;
  op[lastop].op.sphere.r = yyvsp[0].val;
  op[lastop].op.sphere.constants = NULL;
  op[lastop].op.sphere.cs = NULL;
  lastop++;
;
    break;}
case 5:
#line 63 "mdl.y"
{
  lineno++;
  op[lastop].opcode = SPHERE;
  op[lastop].op.sphere.d[0] = yyvsp[-4].val;
  op[lastop].op.sphere.d[1] = yyvsp[-3].val;
  op[lastop].op.sphere.d[2] = yyvsp[-2].val;
  op[lastop].op.sphere.d[3] = 0;
  op[lastop].op.sphere.r = yyvsp[-1].val;
  op[lastop].op.sphere.constants = NULL;
  m = (struct matrix *)new_matrix(4,4);
  op[lastop].op.sphere.cs = add_symbol(yyvsp[0].string,SYM_MATRIX,m);
  lastop++;
;
    break;}
case 6:
#line 77 "mdl.y"
{
  lineno++;
  op[lastop].opcode = SPHERE;
  op[lastop].op.sphere.d[0] = yyvsp[-3].val;
  op[lastop].op.sphere.d[1] = yyvsp[-2].val;
  op[lastop].op.sphere.d[2] = yyvsp[-1].val;
  op[lastop].op.sphere.d[3] = 0;
  op[lastop].op.sphere.r = yyvsp[0].val;
  op[lastop].op.sphere.cs = NULL;
  c = (struct constants *)malloc(sizeof(struct constants));
  op[lastop].op.sphere.constants = add_symbol(yyvsp[-4].string,SYM_CONSTANTS,c);
  lastop++;
;
    break;}
case 7:
#line 91 "mdl.y"
{
  lineno++;
  op[lastop].opcode = SPHERE;
  op[lastop].op.sphere.d[0] = yyvsp[-4].val;
  op[lastop].op.sphere.d[1] = yyvsp[-3].val;
  op[lastop].op.sphere.d[2] = yyvsp[-2].val;
  op[lastop].op.sphere.d[3] = 0;
  op[lastop].op.sphere.r = yyvsp[-1].val;
  op[lastop].op.sphere.constants = NULL;
  m = (struct matrix *)new_matrix(4,4);
  op[lastop].op.sphere.cs = add_symbol(yyvsp[0].string,SYM_MATRIX,m);
  c = (struct constants *)malloc(sizeof(struct constants));
  op[lastop].op.sphere.constants = add_symbol(yyvsp[-5].string,SYM_CONSTANTS,c);
  lastop++;
;
    break;}
case 8:
#line 108 "mdl.y"
{
  lineno++;
  op[lastop].opcode = TORUS;
  op[lastop].op.torus.d[0] = yyvsp[-4].val;
  op[lastop].op.torus.d[1] = yyvsp[-3].val;
  op[lastop].op.torus.d[2] = yyvsp[-2].val;
  op[lastop].op.torus.d[3] = 0;
  op[lastop].op.torus.r0 = yyvsp[-1].val;
  op[lastop].op.torus.r1 = yyvsp[0].val;
  op[lastop].op.torus.constants = NULL;
  op[lastop].op.torus.cs = NULL;

  lastop++;
;
    break;}
case 9:
#line 123 "mdl.y"
{
  lineno++;
  op[lastop].opcode = TORUS;
  op[lastop].op.torus.d[0] = yyvsp[-5].val;
  op[lastop].op.torus.d[1] = yyvsp[-4].val;
  op[lastop].op.torus.d[2] = yyvsp[-3].val;
  op[lastop].op.torus.d[3] = 0;
  op[lastop].op.torus.r0 = yyvsp[-2].val;
  op[lastop].op.torus.r1 = yyvsp[-1].val;
  op[lastop].op.torus.constants = NULL;
  m = (struct matrix *)new_matrix(4,4);
  op[lastop].op.torus.cs = add_symbol(yyvsp[0].string,SYM_MATRIX,m);
  lastop++;
;
    break;}
case 10:
#line 138 "mdl.y"
{
  lineno++;
  op[lastop].opcode = TORUS;
  op[lastop].op.torus.d[0] = yyvsp[-4].val;
  op[lastop].op.torus.d[1] = yyvsp[-3].val;
  op[lastop].op.torus.d[2] = yyvsp[-2].val;
  op[lastop].op.torus.d[3] = 0;
  op[lastop].op.torus.r0 = yyvsp[-1].val;
  op[lastop].op.torus.r1 = yyvsp[0].val;
  op[lastop].op.torus.cs = NULL;
  c = (struct constants *)malloc(sizeof(struct constants));
  op[lastop].op.torus.constants = add_symbol(yyvsp[-5].string,SYM_CONSTANTS,c);

  lastop++;
;
    break;}
case 11:
#line 154 "mdl.y"
{
  lineno++;
  op[lastop].opcode = TORUS;
  op[lastop].op.torus.d[0] = yyvsp[-5].val;
  op[lastop].op.torus.d[1] = yyvsp[-4].val;
  op[lastop].op.torus.d[2] = yyvsp[-3].val;
  op[lastop].op.torus.d[3] = 0;
  op[lastop].op.torus.r0 = yyvsp[-2].val;
  op[lastop].op.torus.r1 = yyvsp[-1].val;
  c = (struct constants *)malloc(sizeof(struct constants));
  op[lastop].op.torus.constants = add_symbol(yyvsp[-6].string,SYM_CONSTANTS,c);
  m = (struct matrix *)new_matrix(4,4);
  op[lastop].op.torus.cs = add_symbol(yyvsp[0].string,SYM_MATRIX,m);

  lastop++;
;
    break;}
case 12:
#line 172 "mdl.y"
{
  lineno++;
  op[lastop].opcode = BOX;
  op[lastop].op.box.d0[0] = yyvsp[-5].val;
  op[lastop].op.box.d0[1] = yyvsp[-4].val;
  op[lastop].op.box.d0[2] = yyvsp[-3].val;
  op[lastop].op.box.d0[3] = 0;
  op[lastop].op.box.d1[0] = yyvsp[-2].val;
  op[lastop].op.box.d1[1] = yyvsp[-1].val;
  op[lastop].op.box.d1[2] = yyvsp[0].val;
  op[lastop].op.box.d1[3] = 0;

  op[lastop].op.box.constants = NULL;
  op[lastop].op.box.cs = NULL;
  lastop++;
;
    break;}
case 13:
#line 189 "mdl.y"
{
  lineno++;
  op[lastop].opcode = BOX;
  op[lastop].op.box.d0[0] = yyvsp[-6].val;
  op[lastop].op.box.d0[1] = yyvsp[-5].val;
  op[lastop].op.box.d0[2] = yyvsp[-4].val;
  op[lastop].op.box.d0[3] = 0;
  op[lastop].op.box.d1[0] = yyvsp[-3].val;
  op[lastop].op.box.d1[1] = yyvsp[-2].val;
  op[lastop].op.box.d1[2] = yyvsp[-1].val;
  op[lastop].op.box.d1[3] = 0;

  op[lastop].op.box.constants = NULL;
  m = (struct matrix *)new_matrix(4,4);
  op[lastop].op.box.cs = add_symbol(yyvsp[0].string,SYM_MATRIX,m);
  lastop++;
;
    break;}
case 14:
#line 207 "mdl.y"
{
  lineno++;
  op[lastop].opcode = BOX;
  op[lastop].op.box.d0[0] = yyvsp[-5].val;
  op[lastop].op.box.d0[1] = yyvsp[-4].val;
  op[lastop].op.box.d0[2] = yyvsp[-3].val;
  op[lastop].op.box.d0[3] = 0;
  op[lastop].op.box.d1[0] = yyvsp[-2].val;
  op[lastop].op.box.d1[1] = yyvsp[-1].val;
  op[lastop].op.box.d1[2] = yyvsp[0].val;
  op[lastop].op.box.d1[3] = 0;
  c = (struct constants *)malloc(sizeof(struct constants));
  op[lastop].op.box.constants = add_symbol(yyvsp[-6].string,SYM_CONSTANTS,c);
  op[lastop].op.box.cs = NULL;
  lastop++;
;
    break;}
case 15:
#line 224 "mdl.y"
{
  lineno++;
  op[lastop].opcode = BOX;
  op[lastop].op.box.d0[0] = yyvsp[-6].val;
  op[lastop].op.box.d0[1] = yyvsp[-5].val;
  op[lastop].op.box.d0[2] = yyvsp[-4].val;
  op[lastop].op.box.d0[3] = 0;
  op[lastop].op.box.d1[0] = yyvsp[-3].val;
  op[lastop].op.box.d1[1] = yyvsp[-2].val;
  op[lastop].op.box.d1[2] = yyvsp[-1].val;
  op[lastop].op.box.d1[3] = 0;
  c = (struct constants *)malloc(sizeof(struct constants));
  op[lastop].op.box.constants = add_symbol(yyvsp[-7].string,SYM_CONSTANTS,c);
  m = (struct matrix *)new_matrix(4,4);
  op[lastop].op.box.cs = add_symbol(yyvsp[0].string,SYM_MATRIX,m);

  lastop++;
;
    break;}
case 16:
#line 244 "mdl.y"
{
  lineno++;
  op[lastop].opcode = LINE;
  op[lastop].op.line.p0[0] = yyvsp[-5].val;
  op[lastop].op.line.p0[1] = yyvsp[-4].val;
  op[lastop].op.line.p0[2] = yyvsp[-3].val;
  op[lastop].op.line.p0[3] = 0;
  op[lastop].op.line.p1[0] = yyvsp[-2].val;
  op[lastop].op.line.p1[1] = yyvsp[-1].val;
  op[lastop].op.line.p1[2] = yyvsp[0].val;
  op[lastop].op.line.p1[3] = 0;
  op[lastop].op.line.constants = NULL;
  op[lastop].op.line.cs0 = NULL;
  op[lastop].op.line.cs1 = NULL;
  lastop++;
;
    break;}
case 17:
#line 262 "mdl.y"
{
  lineno++;
  op[lastop].opcode = LINE;
  op[lastop].op.line.p0[0] = yyvsp[-6].val;
  op[lastop].op.line.p0[1] = yyvsp[-5].val;
  op[lastop].op.line.p0[2] = yyvsp[-4].val;
  op[lastop].op.line.p0[3] = 0;
  op[lastop].op.line.p1[0] = yyvsp[-2].val;
  op[lastop].op.line.p1[1] = yyvsp[-1].val;
  op[lastop].op.line.p1[2] = yyvsp[0].val;
  op[lastop].op.line.p1[3] = 0;
  op[lastop].op.line.constants = NULL;
  m = (struct matrix *)new_matrix(4,4);
  op[lastop].op.line.cs0 = add_symbol(yyvsp[-3].string,SYM_MATRIX,m);
  op[lastop].op.line.cs1 = NULL;
  lastop++;
;
    break;}
case 18:
#line 280 "mdl.y"
{
  lineno++;
  op[lastop].opcode = LINE;
  op[lastop].op.line.p0[0] = yyvsp[-6].val;
  op[lastop].op.line.p0[1] = yyvsp[-5].val;
  op[lastop].op.line.p0[2] = yyvsp[-4].val;
  op[lastop].op.line.p0[3] = 0;
  op[lastop].op.line.p1[0] = yyvsp[-3].val;
  op[lastop].op.line.p1[1] = yyvsp[-2].val;
  op[lastop].op.line.p1[2] = yyvsp[-1].val;
  op[lastop].op.line.p1[3] = 0;
  op[lastop].op.line.constants = NULL;
  op[lastop].op.line.cs0 = NULL;
  m = (struct matrix *)new_matrix(4,4);
  op[lastop].op.line.cs1 = add_symbol(yyvsp[0].string,SYM_MATRIX,m);
  lastop++;
;
    break;}
case 19:
#line 298 "mdl.y"
{
  lineno++;
  op[lastop].opcode = LINE;
  op[lastop].op.line.p0[0] = yyvsp[-7].val;
  op[lastop].op.line.p0[1] = yyvsp[-6].val;
  op[lastop].op.line.p0[2] = yyvsp[-5].val;
  op[lastop].op.line.p0[3] = 0;
  op[lastop].op.line.p1[0] = yyvsp[-3].val;
  op[lastop].op.line.p1[1] = yyvsp[-2].val;
  op[lastop].op.line.p1[2] = yyvsp[-1].val;
  op[lastop].op.line.p1[3] = 0;
  op[lastop].op.line.constants = NULL;
  m = (struct matrix *)new_matrix(4,4);
  op[lastop].op.line.cs0 = add_symbol(yyvsp[-4].string,SYM_MATRIX,m);
  m = (struct matrix *)new_matrix(4,4);
  op[lastop].op.line.cs1 = add_symbol(yyvsp[0].string,SYM_MATRIX,m);
  lastop++;
;
    break;}
case 20:
#line 318 "mdl.y"
{
  lineno++;
  op[lastop].opcode = LINE;
  op[lastop].op.line.p0[0] = yyvsp[-5].val;
  op[lastop].op.line.p0[1] = yyvsp[-4].val;
  op[lastop].op.line.p0[2] = yyvsp[-3].val;
  op[lastop].op.line.p0[3] = 0;
  op[lastop].op.line.p1[0] = yyvsp[-2].val;
  op[lastop].op.line.p1[1] = yyvsp[-1].val;
  op[lastop].op.line.p1[2] = yyvsp[0].val;
  op[lastop].op.line.p1[3] = 0;
  c = (struct constants *)malloc(sizeof(struct constants));
  op[lastop].op.line.constants = add_symbol(yyvsp[-6].string,SYM_CONSTANTS,c);
  op[lastop].op.line.cs0 = NULL;
  op[lastop].op.line.cs1 = NULL;
  lastop++;
;
    break;}
case 21:
#line 336 "mdl.y"
{
  lineno++;
  op[lastop].opcode = LINE;
  op[lastop].op.line.p0[0] = yyvsp[-6].val;
  op[lastop].op.line.p0[1] = yyvsp[-5].val;
  op[lastop].op.line.p0[2] = yyvsp[-4].val;
  op[lastop].op.line.p0[3] = 0;
  op[lastop].op.line.p1[0] = yyvsp[-2].val;
  op[lastop].op.line.p1[1] = yyvsp[-1].val;
  op[lastop].op.line.p1[2] = yyvsp[0].val;
  op[lastop].op.line.p1[3] = 0;
  c = (struct constants *)malloc(sizeof(struct constants));
  op[lastop].op.line.constants = add_symbol(yyvsp[-7].string,SYM_CONSTANTS,c);
  m = (struct matrix *)new_matrix(4,4);
  op[lastop].op.line.cs0 = add_symbol(yyvsp[-3].string,SYM_MATRIX,m);
  op[lastop].op.line.cs1 = NULL;
  lastop++;
;
    break;}
case 22:
#line 355 "mdl.y"
{
  lineno++;
  op[lastop].opcode = LINE;
  op[lastop].op.line.p0[0] = yyvsp[-6].val;
  op[lastop].op.line.p0[1] = yyvsp[-5].val;
  op[lastop].op.line.p0[2] = yyvsp[-4].val;
  op[lastop].op.line.p0[3] = 0;
  op[lastop].op.line.p1[0] = yyvsp[-3].val;
  op[lastop].op.line.p1[1] = yyvsp[-2].val;
  op[lastop].op.line.p1[2] = yyvsp[-1].val;
  op[lastop].op.line.p1[3] = 0;
  c = (struct constants *)malloc(sizeof(struct constants));
  op[lastop].op.line.constants = add_symbol(yyvsp[-7].string,SYM_CONSTANTS,c);
  op[lastop].op.line.cs0 = NULL;
  m = (struct matrix *)new_matrix(4,4);
  op[lastop].op.line.cs1 = add_symbol(yyvsp[0].string,SYM_MATRIX,m);
  op[lastop].op.line.cs0 = NULL;
  lastop++;
;
    break;}
case 23:
#line 375 "mdl.y"
{
  lineno++;
  op[lastop].opcode = LINE;
  op[lastop].op.line.p0[0] = yyvsp[-7].val;
  op[lastop].op.line.p0[1] = yyvsp[-6].val;
  op[lastop].op.line.p0[2] = yyvsp[-5].val;
  op[lastop].op.line.p0[3] = 0;
  op[lastop].op.line.p1[0] = yyvsp[-3].val;
  op[lastop].op.line.p1[1] = yyvsp[-2].val;
  op[lastop].op.line.p1[2] = yyvsp[-1].val;
  op[lastop].op.line.p1[3] = 0;
  c = (struct constants *)malloc(sizeof(struct constants));
  op[lastop].op.line.constants = add_symbol(yyvsp[-8].string,SYM_CONSTANTS,c);
  m = (struct matrix *)new_matrix(4,4);
  op[lastop].op.line.cs0 = add_symbol(yyvsp[-4].string,SYM_MATRIX,m);
  m = (struct matrix *)new_matrix(4,4);
  op[lastop].op.line.cs1 = add_symbol(yyvsp[0].string,SYM_MATRIX,m);
  lastop++;
;
    break;}
case 24:
#line 396 "mdl.y"
{
  lineno++;
  op[lastop].opcode = MESH;
  strcpy(op[lastop].op.mesh.name,yyvsp[0].string);
  op[lastop].op.mesh.constants = NULL;
  op[lastop].op.mesh.cs = NULL;
  lastop++;
;
    break;}
case 25:
#line 405 "mdl.y"
{ /* name and constants */
  lineno++;
  op[lastop].opcode = MESH;
  strcpy(op[lastop].op.mesh.name,yyvsp[0].string);
  c = (struct constants *)malloc(sizeof(struct constants));
  op[lastop].op.mesh.constants = add_symbol(yyvsp[-2].string,SYM_CONSTANTS,c);
  op[lastop].op.mesh.cs = NULL;
  lastop++;
;
    break;}
case 26:
#line 415 "mdl.y"
{
  lineno++;
  op[lastop].opcode = MESH;
  strcpy(op[lastop].op.mesh.name,yyvsp[-1].string);
  c = (struct constants *)malloc(sizeof(struct constants));
  op[lastop].op.mesh.constants = add_symbol(yyvsp[-3].string,SYM_CONSTANTS,c);
  m = (struct matrix *)new_matrix(4,4);
  op[lastop].op.mesh.cs = add_symbol(yyvsp[0].string,SYM_MATRIX,m);
  lastop++;
;
    break;}
case 27:
#line 427 "mdl.y"
{
  lineno++;
  op[lastop].opcode = MOVE;
  op[lastop].op.move.d[0] = yyvsp[-3].val;
  op[lastop].op.move.d[1] = yyvsp[-2].val;
  op[lastop].op.move.d[2] = yyvsp[-1].val;
  op[lastop].op.move.d[3] = 0;
  op[lastop].op.move.p = add_symbol(yyvsp[0].string,SYM_VALUE,0);
  lastop++;
;
    break;}
case 28:
#line 438 "mdl.y"
{
  lineno++;
  op[lastop].opcode = MOVE;
  op[lastop].op.move.d[0] = yyvsp[-2].val;
  op[lastop].op.move.d[1] = yyvsp[-1].val;
  op[lastop].op.move.d[2] = yyvsp[0].val;
  op[lastop].op.move.d[3] = 0;
  op[lastop].op.move.p = NULL;
  lastop++;
;
    break;}
case 29:
#line 450 "mdl.y"
{
  lineno++;
  op[lastop].opcode = SCALE;
  op[lastop].op.scale.d[0] = yyvsp[-3].val;
  op[lastop].op.scale.d[1] = yyvsp[-2].val;
  op[lastop].op.scale.d[2] = yyvsp[-1].val;
  op[lastop].op.scale.d[3] = 0;
  op[lastop].op.scale.p = add_symbol(yyvsp[0].string,SYM_VALUE,0);
  lastop++;
;
    break;}
case 30:
#line 461 "mdl.y"
{
  lineno++;
  op[lastop].opcode = SCALE;
  op[lastop].op.scale.d[0] = yyvsp[-2].val;
  op[lastop].op.scale.d[1] = yyvsp[-1].val;
  op[lastop].op.scale.d[2] = yyvsp[0].val;
  op[lastop].op.scale.d[3] = 0;
  op[lastop].op.scale.p = NULL;
  lastop++;
;
    break;}
case 31:
#line 472 "mdl.y"
{
  lineno++;
  op[lastop].opcode = ROTATE;
  switch (*yyvsp[-2].string)
    {
    case 'x':
    case 'X':
      op[lastop].op.rotate.axis = 0;
      break;
    case 'y':
    case 'Y':
      op[lastop].op.rotate.axis = 1;
      break;
    case 'z':
    case 'Z':
      op[lastop].op.rotate.axis = 2;
      break;
    }

  op[lastop].op.rotate.degrees = yyvsp[-1].val;
  op[lastop].op.rotate.p = add_symbol(yyvsp[0].string,SYM_VALUE,0);
  lastop++;
;
    break;}
case 32:
#line 496 "mdl.y"
{
  lineno++;
  op[lastop].opcode = ROTATE;
  switch (*yyvsp[-1].string)
    {
    case 'x':
    case 'X':
      op[lastop].op.rotate.axis = 0;
      break;
    case 'y':
    case 'Y':
      op[lastop].op.rotate.axis = 1;
      break;
    case 'z':
    case 'Z':
      op[lastop].op.rotate.axis = 2;
      break;
    }
  op[lastop].op.rotate.degrees = yyvsp[0].val;
  op[lastop].op.rotate.p = NULL;
  lastop++;
;
    break;}
case 33:
#line 520 "mdl.y"
{
  lineno++;
  op[lastop].opcode = PUSH;
  lastop++;
;
    break;}
case 34:
#line 527 "mdl.y"
{
  lineno++;
  op[lastop].opcode = POP;
  lastop++;
;
    break;}
case 35:
#line 534 "mdl.y"
{
  lineno++;
  op[lastop].opcode = DISPLAY;
  lastop++;
;
    break;}
case 36:
#line 541 "mdl.y"
{
  lineno++;
  op[lastop].opcode = SAVE;
  op[lastop].op.save.p = add_symbol(yyvsp[0].string,SYM_FILE,0);
  lastop++;
;
    break;}
case 37:
#line 549 "mdl.y"
{
  lineno++;
  l = (struct light *)malloc(sizeof(struct light));
  l->l[0]= yyvsp[-5].val;
  l->l[1]= yyvsp[-4].val;
  l->l[2]= yyvsp[-3].val;
  l->l[3]= 0;
  l->c[0]= yyvsp[-2].val;
  l->c[1]= yyvsp[-1].val;
  l->c[2]= yyvsp[0].val;
  op[lastop].opcode=LIGHT;
  op[lastop].op.light.c[0] = yyvsp[-2].val;
  op[lastop].op.light.c[1] = yyvsp[-1].val;
  op[lastop].op.light.c[2] = yyvsp[0].val;
  op[lastop].op.light.c[3] = 0;
  op[lastop].op.light.p = add_symbol(yyvsp[-6].string,SYM_LIGHT,l);
  lastop++;
;
    break;}
case 38:
#line 569 "mdl.y"
{
  lineno++;
  c = (struct constants *)malloc(sizeof(struct constants));
  c->r[0]=yyvsp[-8].val;
  c->r[1]=yyvsp[-7].val;
  c->r[2]=yyvsp[-6].val;
  c->r[3]=0;

  c->g[0]=yyvsp[-5].val;
  c->g[1]=yyvsp[-4].val;
  c->g[2]=yyvsp[-3].val;
  c->g[3]=0;

  c->b[0]=yyvsp[-2].val;
  c->b[1]=yyvsp[-1].val;
  c->b[2]=yyvsp[0].val;
  c->b[3]=0;

  c->red = 0;
  c->green = 0;
  c->blue = 0;

  op[lastop].op.constants.p =  add_symbol(yyvsp[-9].string,SYM_CONSTANTS,c);
  op[lastop].opcode=CONSTANTS;
  lastop++;
;
    break;}
case 39:
#line 597 "mdl.y"
{
  lineno++;
  c = (struct constants *)malloc(sizeof(struct constants));
  c->r[0]=yyvsp[-11].val;
  c->r[1]=yyvsp[-10].val;
  c->r[2]=yyvsp[-9].val;
  c->r[3]=0;

  c->g[0]=yyvsp[-8].val;
  c->g[1]=yyvsp[-7].val;
  c->g[2]=yyvsp[-6].val;
  c->g[3]=0;

  c->b[0]=yyvsp[-5].val;
  c->b[1]=yyvsp[-4].val;
  c->b[2]=yyvsp[-3].val;
  c->b[3]=0;

  c->red = yyvsp[-2].val;
  c->green = yyvsp[-1].val;
  c->blue = yyvsp[0].val;
  op[lastop].op.constants.p =  add_symbol(yyvsp[-12].string,SYM_CONSTANTS,c);
  op[lastop].opcode=CONSTANTS;
  lastop++;
;
    break;}
case 40:
#line 624 "mdl.y"
{
  lineno++;
  op[lastop].opcode = SAVE_COORDS;
  m = new_matrix(4,4);
  op[lastop].op.save_coordinate_system.p = add_symbol(yyvsp[0].string,SYM_MATRIX,m);
  lastop++;
;
    break;}
case 41:
#line 633 "mdl.y"
{
  lineno++;
  op[lastop].opcode = CAMERA;
  op[lastop].op.camera.eye[0] = yyvsp[-5].val;
  op[lastop].op.camera.eye[1] = yyvsp[-4].val;
  op[lastop].op.camera.eye[2] = yyvsp[-3].val;
  op[lastop].op.camera.eye[3] = 0;
  op[lastop].op.camera.aim[0] = yyvsp[-2].val;
  op[lastop].op.camera.aim[1] = yyvsp[-1].val;
  op[lastop].op.camera.aim[2] = yyvsp[0].val;
  op[lastop].op.camera.aim[3] = 0;
  lastop++;
;
    break;}
case 42:
#line 648 "mdl.y"
{
  lineno++;
  op[lastop].opcode = TEXTURE;
  c = (struct constants *)malloc(sizeof(struct constants));
  op[lastop].op.texture.d0[0] = yyvsp[-11].val;
  op[lastop].op.texture.d0[1] = yyvsp[-10].val;
  op[lastop].op.texture.d0[2] = yyvsp[-9].val;
  op[lastop].op.texture.d1[0] = yyvsp[-8].val;
  op[lastop].op.texture.d1[1] = yyvsp[-7].val;
  op[lastop].op.texture.d1[2] = yyvsp[-6].val;
  op[lastop].op.texture.d2[0] = yyvsp[-5].val;
  op[lastop].op.texture.d2[1] = yyvsp[-4].val;
  op[lastop].op.texture.d2[2] = yyvsp[-3].val;
  op[lastop].op.texture.d3[0] = yyvsp[-2].val;
  op[lastop].op.texture.d3[1] = yyvsp[-1].val;
  op[lastop].op.texture.d3[2] = yyvsp[0].val;
  op[lastop].op.texture.cs = NULL;
  op[lastop].op.texture.constants =  add_symbol("",SYM_CONSTANTS,c);
  op[lastop].op.texture.p = add_symbol(yyvsp[-12].string,SYM_FILE,0);
  lastop++;
;
    break;}
case 43:
#line 671 "mdl.y"
{
  lineno++;
  op[lastop].opcode = SET;
  op[lastop].op.set.p = add_symbol(yyvsp[-1].string,SYM_VALUE,0);
  set_value(op[lastop].op.set.p,yyvsp[0].val);
  op[lastop].op.set.val = yyvsp[0].val;
  lastop++;
;
    break;}
case 44:
#line 681 "mdl.y"
{
  lineno++;
  op[lastop].opcode = BASENAME;
  op[lastop].op.basename.p = add_symbol(yyvsp[0].string,SYM_STRING,0);
  lastop++;
;
    break;}
case 45:
#line 688 "mdl.y"
{
  lineno++;
  op[lastop].opcode = SAVE_KNOBS;
  op[lastop].op.save_knobs.p = add_symbol(yyvsp[0].string,SYM_STRING,0);
  lastop++;
;
    break;}
case 46:
#line 696 "mdl.y"
{
  lineno++;
  op[lastop].opcode = TWEEN;
  op[lastop].op.tween.start_frame = yyvsp[-3].val;
  op[lastop].op.tween.end_frame = yyvsp[-2].val;
  op[lastop].op.tween.knob_list0 = add_symbol(yyvsp[-1].string,SYM_STRING,0);
  op[lastop].op.tween.knob_list1 = add_symbol(yyvsp[0].string,SYM_STRING,0);
  lastop++;
;
    break;}
case 47:
#line 707 "mdl.y"
{
  lineno++;
  op[lastop].opcode = FRAMES;
  op[lastop].op.frames.num_frames = yyvsp[0].val;
  lastop++;
;
    break;}
case 48:
#line 715 "mdl.y"
{
  lineno++;
  op[lastop].opcode = VARY;
  op[lastop].op.vary.p = add_symbol(yyvsp[-4].string,SYM_STRING,0);
  op[lastop].op.vary.start_frame = yyvsp[-3].val;
  op[lastop].op.vary.end_frame = yyvsp[-2].val;
  op[lastop].op.vary.start_val = yyvsp[-1].val;
  op[lastop].op.vary.end_val = yyvsp[0].val;
  lastop++;
;
    break;}
case 49:
#line 727 "mdl.y"
{
  lineno++;
  op[lastop].opcode = SHADING;
  op[lastop].op.shading.p = add_symbol(yyvsp[0].string,SYM_STRING,0);
  lastop++;
;
    break;}
case 50:
#line 734 "mdl.y"
{
  lineno++;
  op[lastop].opcode = SETKNOBS;
  op[lastop].op.setknobs.value = yyvsp[0].val;
  lastop++;
;
    break;}
case 51:
#line 741 "mdl.y"
{
  lineno++;
  op[lastop].opcode = FOCAL;
  op[lastop].op.focal.value = yyvsp[0].val;
  lastop++;
;
    break;}
case 52:
#line 749 "mdl.y"
{
  lineno++;
  op[lastop].opcode = WEB;
  lastop++;
;
    break;}
case 53:
#line 755 "mdl.y"
{
  lineno++;
  op[lastop].opcode = AMBIENT;
  op[lastop].op.ambient.c[0] = yyvsp[-2].val;
  op[lastop].op.ambient.c[1] = yyvsp[-1].val;
  op[lastop].op.ambient.c[2] = yyvsp[0].val;
  lastop++;
;
    break;}
case 54:
#line 765 "mdl.y"
{
  lineno++;
  op[lastop].opcode = GENERATE_RAYFILES;
  lastop++;
;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 770 "mdl.y"



/* Other C stuff */
int yyerror(char *s)
{
  printf("Error in line %d:%s\n",lineno,s);
  return 0;
}

int yywrap()
{
  return 1;
}


extern FILE *yyin;


int main(int argc, char **argv) {

  yyin = fopen(argv[1],"r");

  yyparse();
  //COMMENT OUT PRINT_PCODE AND UNCOMMENT
  //MY_MAIN IN ORDER TO RUN YOUR CODE

  print_pcode();
  //my_main();

  return 0;
}
